services:
    kiwix-serve:
        image: ghcr.io/kiwix/kiwix-serve:latest
        container_name: kiwix
        volumes:
            - /media/kiwix:/data
        ports:
            - "8081:8080"
        command:
            '*.zim'
        restart: unless-stopped
networks:
    default:
        external: true
        name: reverse-proxy
