services:
    kiwix-serve:
        image: ghcr.io/kiwix/kiwix-serve:latest
        container_name: kiwix
        volumes:
            - /media/kiwix:/data
        command:
            '*.zim'
        restart: unless-stopped
networks:
    default:
        external: true
        name: reverse-proxy
